services:

  # database
  db:
    image: postgres:latest
    restart: always
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: tasksmanager
      POSTGRES_PASSWORD: postgres_pwd
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tasksmanager"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - task-manager

  # database admin page
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - task-manager

volumes:
  postgres_data:

networks:
  task-manager:
