services:
  api:
    container_name: api
    build:
      context: .
      target: builder
    env_file: .env.dev
    command: uv run uvicorn app.asgi:app --host 0.0.0.0 --port 8000 --reload --no-access-log
    volumes:
    - ./app:/app/app
    ports:
      - "8000:8000"
    networks:
      - task-manager
    depends_on:
      db:
        condition: service_healthy
  
  # database used of testing
  db-test:
    image: postgres:latest
    restart: always
    container_name: postgres_db_test
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: tasksmanager
      POSTGRES_PASSWORD: postgres_pwd
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tasksmanager"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - task-manager

volumes:
  postgres_data_test:
