[project]
name = "task-manager-backend"
version = "0.1.0"
description = "Backend for the Task Manager app"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.139.2",
    "pwdlib[argon2]>=0.3.0",
    "pydantic[email]>=2.13.4",
    "pydantic-settings>=2.14.2",
    "pyjwt[crypto]>=2.13.0",
    "python-dateutil>=2.9.0.post0",
    "sqlmodel>=0.0.39",
    "uvicorn>=0.51.0",
    "psycopg2-binary>=2.9.12",
]

[tool.pyright]
venv = ".venv"
venvPath = "."
